// VIVA GUIDE: Explicit regression/fixture tool: inspect assertions and cleanup; database checks use their configured database. Standalone test or diagnostic program. Read fixture setup, assertions and cleanup; do not assume Maven package executes this file.
import com.queue.service.*;import com.queue.util.*;import java.sql.*;import java.time.*;import java.util.*;
class AnalyticsChecks {
 // Operation insert: follow the inputs, validation and return value in the block below; the file header explains its layer/caller.
 static int insert(Connection c,String sql,Object...a)throws Exception{try(PreparedStatement p=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){for(int i=0;i<a.length;i++)p.setObject(i+1,a[i]);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){return r.next()?r.getInt(1):0;}}}
 // Standalone entry point: runs this diagnostic/setup/check explicitly; Maven packaging does not automatically execute it.
 public static void main(String[]args)throws Exception {int service=0,student=0;try(Connection c=DBConnection.getConnection()) {try{service=insert(c,"INSERT INTO services(service_name,description,average_service_time) VALUES (?,'Analytics test fixture',5)","Analytics "+UUID.randomUUID());student=insert(c,"INSERT INTO students(student_name,email,password) VALUES ('Analytics fixture',?,'unused')",UUID.randomUUID()+"@invalid");LocalDate day=ServiceHours.now().toLocalDate();
 for(int i=0;i<4;i++){String status=i==1?"CANCELLED":i==2?"NO_SHOW":"COMPLETED";LocalDate d=i==3?day.minusDays(1):day;int id=insert(c,"INSERT INTO queue(student_id,service_id,token_number,status,joined_at,started_at,completed_at) VALUES (?,?,?,?,?,?,?)",student,service,i+1,status,d.atTime(10,0),d.atTime(10,i==1?50:10),d.atTime(10,15));insert(c,"INSERT INTO queue_reservations(queue_id,visit_date,queue_order) VALUES (?,?,?)",id,d,i+1);}
 if(ServiceHours.processingMinutes(day.atTime(7,0),day.atTime(10,5))!=5.0||ServiceHours.processingMinutes(day.atTime(12,55),day.atTime(14,5))!=10.0||ServiceHours.processingMinutes(day.atTime(15,0),day.plusDays(1).atTime(10,5))!=5.0)throw new AssertionError("Closed hours counted");
 if(new WaitingTimeService().getAverageServiceTime(service)!=5.0)throw new AssertionError("Service average counted prebooking or cancellation");
 if(ServiceHours.processingMinutes(day.atTime(10,0),day.atTime(10,3))!=3.0 || !ServiceHours.project(day.atTime(8,0),3).equals(day.atTime(10,3)))throw new AssertionError("Second prebooking should be estimated at 10:03 for a three-minute service");
 System.out.println("PASS estimate uses staff processing duration and excludes early booking, lunch and overnight");
 Map<String,Object> m=new AnalyticsService().getServiceDaySummary(service);if(!m.get("servedToday").equals(1)||!m.get("noShowsToday").equals(1)||!m.get("averageWaitMinutes").equals(10.0)||!m.get("averageServiceMinutes").equals(5.0))throw new AssertionError(m);System.out.println("PASS today's completed count, actual wait/service durations, no-show status, cancellation and prior-day exclusion");
 }finally {if(service>0){try(PreparedStatement p=c.prepareStatement("DELETE FROM queue WHERE service_id=?")){p.setInt(1,service);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("DELETE FROM services WHERE service_id=?")){p.setInt(1,service);p.executeUpdate();}}if(student>0){try(PreparedStatement p=c.prepareStatement("DELETE FROM students WHERE student_id=?")){p.setInt(1,student);p.executeUpdate();}}System.out.println("Own analytics fixtures removed.");}}}
}
